/**
 * Snapshot реальных свечей SBER за 2026-04-21 (60-минутный таймфрейм).
 * Запускается вручную: `npx tsx scripts/landing-assets/snapshot-moex-candles.ts`
 * Идемпотентный — пишет тот же файл при повторном запуске.
 *
 * Источник: MOEX ISS API engines/stock/markets/shares/securities/SBER/candles
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

type Candle = { t: string; o: number; h: number; l: number; c: number; v: number };

const SYMBOL = "SBER";
const FROM = "2026-04-21T07:00:00";
const TO = "2026-04-21T16:00:00";
const INTERVAL = 60; // минуты

async function main() {
  const url =
    `https://iss.moex.com/iss/engines/stock/markets/shares/securities/${SYMBOL}/candles.json` +
    `?from=${FROM}&till=${TO}&interval=${INTERVAL}&iss.meta=off`;

  const res = await fetch(url);
  if (!res.ok) throw new Error(`MOEX returned ${res.status}`);
  const json = await res.json();
  const cols: string[] = json.candles.columns;
  const rows: unknown[][] = json.candles.data;

  const iO = cols.indexOf("open"),
    iH = cols.indexOf("high"),
    iL = cols.indexOf("low"),
    iC = cols.indexOf("close"),
    iV = cols.indexOf("value"),
    iB = cols.indexOf("begin");

  const candles: Candle[] = rows.map((r) => ({
    t: String(r[iB]),
    o: Number(r[iO]),
    h: Number(r[iH]),
    l: Number(r[iL]),
    c: Number(r[iC]),
    v: Number(r[iV]),
  }));

  if (candles.length < 4) throw new Error(`too few candles: ${candles.length}`);

  const out = resolve("src/components/landing/data/sber-candles-2026-04-21.ts");
  const body =
    `// AUTO-GENERATED by scripts/landing-assets/snapshot-moex-candles.ts\n` +
    `// Source: MOEX ISS · ${SYMBOL} · ${FROM}..${TO} · ${INTERVAL}m\n` +
    `export type Candle = { t: string; o: number; h: number; l: number; c: number; v: number };\n` +
    `export const sberCandles: Candle[] = ${JSON.stringify(candles, null, 2)};\n`;
  writeFileSync(out, body, "utf8");
  console.log(`wrote ${candles.length} candles → ${out}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
