"""Initial migration

Revision ID: 60a8c581cd18
Revises: 
Create Date: 2026-01-05 08:56:46.522219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60a8c581cd18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'plan',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('FREE', 'PRO', 'CORPORATE', name='subscriptionplan'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'plan',
               existing_type=sa.Enum('FREE', 'PRO', 'CORPORATE', name='subscriptionplan'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
