#!/usr/bin/env bash
# ============================================================================
#  scripts/load_secrets.sh (INFRA-07)
#  Выгружает Empirik production secrets из Yandex Lockbox в .env-файл.
#
#  Использование:
#     LOCKBOX_SECRET_ID=e6q12345... ./scripts/load_secrets.sh [output_path]
#
#  По умолчанию пишет в /opt/empirik/.env (mode 600, owner текущий).
#  Требования: yc CLI установлен и аутентифицирован (`yc init` или $YC_TOKEN),
#  jq для парсинга JSON-payload.
#
#  Ротация: обнови entry в Lockbox UI → запусти этот скрипт → рестартуй
#  backend/frontend (см. docs/RUNBOOK.md → Secret management).
# ============================================================================
set -euo pipefail

# ─── Аргументы и валидация ───
LOCKBOX_SECRET_ID="${LOCKBOX_SECRET_ID:?LOCKBOX_SECRET_ID env variable required (find in console.yandex.cloud → Lockbox)}"
OUTPUT="${1:-/opt/empirik/.env}"

# ─── Проверка зависимостей ───
if ! command -v yc >/dev/null 2>&1; then
    echo "ERROR: yc CLI not found. Install: https://yandex.cloud/docs/cli/quickstart" >&2
    exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
    echo "ERROR: jq required. Ubuntu: apt-get install -y jq | macOS: brew install jq" >&2
    exit 1
fi

# ─── Подтянуть payload ───
echo "[load_secrets] Fetching Lockbox secret ${LOCKBOX_SECRET_ID}..."
PAYLOAD="$(yc lockbox payload get --id "$LOCKBOX_SECRET_ID" --format json)"

if [ -z "$PAYLOAD" ]; then
    echo "ERROR: Empty payload from Lockbox (wrong ID? no access? secret deactivated?)" >&2
    exit 1
fi

# ─── Подготовка output-директории ───
OUTPUT_DIR="$(dirname -- "$OUTPUT")"
if [ ! -d "$OUTPUT_DIR" ]; then
    mkdir -p "$OUTPUT_DIR"
fi

# ─── Атомарная запись (через .tmp + mv) ───
# Lockbox entries имеют поле text_value ИЛИ binary_value (base64). jq fallback
# на binary_value через `//` — это запишет уже-декодированную строку (т.к.
# `yc` отдаёт текстом обоих типов; binary остаётся base64-строкой, что нам и нужно
# для ключей типа MASTER_KEY_B64).
TMP="${OUTPUT}.tmp.$$"
trap 'rm -f "$TMP"' EXIT

# Header — комментарий о происхождении файла, чтобы случайно не закоммитили.
{
    echo "# Empirik production secrets — DO NOT COMMIT."
    echo "# Generated by scripts/load_secrets.sh from Yandex Lockbox ${LOCKBOX_SECRET_ID}"
    echo "# Generated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "#"
    echo "$PAYLOAD" | jq -r '.entries[] | "\(.key)=\(.text_value // .binary_value)"'
} > "$TMP"

mv "$TMP" "$OUTPUT"
trap - EXIT
chmod 600 "$OUTPUT"

# ─── Самопроверка: required-keys ───
# Минимум для старта backend в prod. Отсутствие = WARNING (не fail, потому что
# Lockbox мог быть staging-вариантом с pre-filled defaults).
REQUIRED_KEYS=(SECRET_KEY REFRESH_SECRET_KEY MASTER_KEY_B64 DATABASE_URL REDIS_URL)
MISSING=()
for key in "${REQUIRED_KEYS[@]}"; do
    if ! grep -q "^${key}=" "$OUTPUT"; then
        MISSING+=("$key")
    fi
done

if [ "${#MISSING[@]}" -gt 0 ]; then
    echo "[load_secrets] WARNING: required keys missing from payload: ${MISSING[*]}" >&2
    echo "[load_secrets] Backend probably WILL NOT START. Add them to Lockbox and re-run." >&2
fi

echo "[load_secrets] Wrote $OUTPUT (mode 600, $(wc -l < "$OUTPUT") lines)"
echo "[load_secrets] Required:  SECRET_KEY REFRESH_SECRET_KEY MASTER_KEY_B64 DATABASE_URL REDIS_URL"
echo "[load_secrets] Optional:  SENTRY_DSN NEXT_PUBLIC_SENTRY_DSN SMTP_* OAUTH_* BACKUP_S3_* WALG_*"
